apikey: "41690931e4234e98a3822cefa3ee9f69"
baseUrl: "https://api.sl.se/api2/linedata.json?key={key}&DefaultTransportModeCode={code}&model={model}"

spring:
  cache:
    cache-names: "trafiklab"
    caffeine:
      spec: maximumSize=100
  codec:
    max-in-memory-size: 10MB

---
spring:
  profiles: test

apikey: "nothing"
baseUrl: "http://localhost:8080?key={key}&DefaultTransportModeCode={code}&model={model}"
